import { useEffect, useState } from 'react';
import type { Audit, User } from '../types';
import { api } from '../api';
import { Alert, Button, Loading, Modal, PageHeading } from '../components/UI';
export function AdminPage() {
  const [tab, setTab] = useState<'users' | 'logs'>('users'), [offset, setOffset] = useState({ users: 0, logs: 0 });
  const [users, setUsers] = useState<User[]>([]), [logs, setLogs] = useState<Audit[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(false), [saving, setSaving] = useState(false), [target, setTarget] = useState<User | null>(null), [revision, setRevision] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setError(''); const request = tab === 'users' ? api<User[]>('/admin/users?offset=' + offset.users) : api<Audit[]>('/admin/logs?offset=' + offset.logs); request.then(data => { if (active) { if (tab === 'users') setUsers(data as User[]); else setLogs(data as Audit[]); } }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [tab, offset.users, offset.logs, revision]);
  return <><PageHeading eyebrow="ADMINISTRATION" title="Keep the learning space healthy." description="Manage account access and review recorded activity."/><div className="filter-tabs admin-tabs"><button aria-pressed={tab === 'users'} onClick={() => setTab('users')}>User accounts</button><button aria-pressed={tab === 'logs'} onClick={() => setTab('logs')}>Audit trail</button></div>{error && <Alert error>{error}<Button variant="ghost" onClick={() => setRevision(revision + 1)}>Retry</Button></Alert>}{loading ? <Loading/> : <section className="panel table-panel"><div className="table-scroll">{tab === 'users' ? <table><caption className="sr-only">User accounts and access controls</caption><thead><tr><th>Account</th><th>Role</th><th>Status</th><th>Access</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td>{user.role}</td><td><span className={`status-badge ${user.suspended ? 'status-warning' : 'status-success'}`}>{user.suspended ? 'Suspended' : 'Active'}</span></td><td>{user.role === 'admin' ? <small>Protected admin</small> : <Button variant="secondary" onClick={() => setTarget(user)}>{user.suspended ? 'Restore' : 'Suspend'}</Button>}</td></tr>)}</tbody></table> : <table><caption className="sr-only">Recorded application audit events</caption><thead><tr><th>Event</th><th>Actor / target</th><th>Recorded</th></tr></thead><tbody>{logs.map((log, index) => <tr key={index}><td>{log.action.replaceAll('_', ' ')}</td><td className="audit-id">{log.actor_id}{log.target_id && <small>Target: {log.target_id}</small>}</td><td>{new Date(log.date).toLocaleString()}</td></tr>)}</tbody></table>}</div>{!(tab === 'users' ? users.length : logs.length) && <p className="table-empty">No more records on this page.</p>}</section>}<div className="pagination"><Button variant="secondary" disabled={loading || offset[tab] === 0} onClick={() => setOffset({ ...offset, [tab]: Math.max(0, offset[tab] - 100) })}>Previous</Button><span>Page {offset[tab] / 100 + 1}</span><Button variant="secondary" disabled={loading || (tab === 'users' ? users.length : logs.length) < 100} onClick={() => setOffset({ ...offset, [tab]: offset[tab] + 100 })}>Next</Button></div>{target && <Modal title={`${target.suspended ? 'Restore' : 'Suspend'} ${target.name}?`} subtitle={target.suspended ? 'This learner will be able to sign in again.' : 'This immediately revokes their sessions and prevents access.'} busy={saving} onClose={() => setTarget(null)}><div className="button-row"><Button disabled={saving} onClick={async () => { setSaving(true); try { await api('/admin/users/' + target.id, 'PATCH', { suspended: !target.suspended }); setTarget(null); setRevision(revision + 1); } catch (err) { setError((err as Error).message); setTarget(null); } finally { setSaving(false); } }}>{saving ? 'Updating…' : 'Confirm'}</Button><Button variant="secondary" disabled={saving} onClick={() => setTarget(null)}>Cancel</Button></div></Modal>}</>;
}
