import { ArrowRight, ArrowUpRight, BookOpen, Check, Clock3, Plus, Target, Zap } from 'lucide-react';
import type { Course, Credential, Report, User } from '../types';
import { Button, Empty, PageHeading, Progress, Status } from '../components/UI';
export function Dashboard({ user, courses, report, credential, open, create, navigate }: {
  user: User; courses: Course[]; report: Report; credential: Credential; open: (course: Course) => void; create: (practice?: boolean) => void; navigate: (page: string) => void;
}) {
  const paths = courses.filter(course => !course.practice);
  const current = paths.find(course => !course.complete);
  const completed = paths.reduce((count, course) => count + course.current, 0);
  const average = report.attempts.length ? Math.round(report.attempts.reduce((sum, attempt) => sum + attempt.score, 0) / report.attempts.length) : null;
  const strengths = report.skills.filter(skill => skill.score >= 80);
  const recent = report.attempts.slice(-3).reverse();
  return <>
    <PageHeading eyebrow="YOUR PERSONAL LEARNING DESK" title={`A little further, ${user.name.split(' ')[0]}.`} description="Pick up a thread. Follow a question. Learn something that stays." action={<Button onClick={() => create()}><Plus size={18} aria-hidden="true"/>New learning path</Button>}/>
    <div className="metric-strip">{[[String(paths.length).padStart(2, '0'), 'Learning paths'], [String(completed).padStart(2, '0'), 'Missions covered'], [average === null ? '—' : average + '%', 'Average quiz score'], [String(strengths.length).padStart(2, '0'), 'Assessed strengths']].map(([value, label]) => <div className="metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
    <div className="dashboard-columns"><div className="dashboard-main">
      <div className="section-heading"><h2>On your desk</h2><a href="#learning">All learning paths<ArrowUpRight size={15} aria-hidden="true"/></a></div>
      <article className="featured-path"><div className="featured-copy"><span className="eyebrow">{current ? 'CONTINUE YOUR LEARNING' : 'AN OPEN PAGE. A FRESH START.'}</span><h2>{current ? current.title : 'A new interest starts here.'}</h2><p>{current ? current.missions[current.current].objective : 'Choose something you’re curious about. We’ll help you turn it into something you understand.'}</p>{current && <div className="featured-progress"><div><span>Mission {current.current + 1} of {current.missions.length}</span><span>{Math.round(current.current / current.missions.length * 100)}% covered</span></div><Progress value={current.current / current.missions.length * 100} label="Learning path progress"/></div>}<Button variant="dark" onClick={() => current ? open(current) : create()}>{current ? current.pending_attempt ? 'Choose your next step' : 'Continue learning' : 'Create your first path'}<ArrowRight size={18} aria-hidden="true"/></Button></div><div className="path-art" aria-hidden="true"><div className="art-outline"/><span className="art-index">{String((current?.current || 0) + 1).padStart(2, '0')}</span><span className="art-caption">THE NEXT<br/>GOOD QUESTION.</span><ArrowUpRight size={54} strokeWidth={1}/></div></article>
      <article className="practice-callout"><span className="round-icon"><Zap size={24} aria-hidden="true"/></span><div><span className="eyebrow">A QUICK MENTAL WORKOUT</span><h3>Just here for a quiz?</h3><p>Practice any topic. No whole course required.</p></div><Button variant="secondary" onClick={() => create(true)}>Open practice studio<ArrowUpRight size={16} aria-hidden="true"/></Button></article>
      <div className="section-heading"><h2>Recent work</h2><a href="#growth">Your growth report<ArrowUpRight size={15} aria-hidden="true"/></a></div>
      <div className="activity-list">{recent.length ? recent.map(attempt => <div className="activity-row" key={attempt.id}><span className="activity-icon"><Check size={18} aria-hidden="true"/></span><div><strong>{courses.find(course => course.id === attempt.course_id)?.title || 'Learning assessment'}</strong><span>{new Date(attempt.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} · Quiz completed</span></div><strong className="activity-score">{attempt.score}<small>%</small></strong></div>) : <div className="activity-empty"><Clock3 size={21} aria-hidden="true"/><div><strong>Your first session belongs here.</strong><p>Complete a mission or practice quiz to start your record.</p></div></div>}</div>
    </div><aside className="dashboard-aside">
      <div className="section-heading"><h2>Your skill notes</h2><Target size={18} aria-hidden="true"/></div>
      <section className="skill-panel"><span className="eyebrow">WHAT THE EVIDENCE SAYS</span><h3>{report.skills.length ? 'Know your next move.' : 'Get to know your strengths.'}</h3><p>{report.skills.length ? 'Every quiz gives you something to build on.' : 'Your skill map starts with your first quiz. No guesses. Just your results.'}</p>{report.skills.slice(0, 4).map(skill => <div className="mini-skill" key={skill.name}><div><span>{skill.name}</span><strong>{skill.score}%</strong></div><Progress value={skill.score} label={`${skill.name} score`}/><small>{skill.score >= 80 ? 'A growing strength' : 'Worth another look'}</small></div>)}{!report.skills.length && <div className="skill-placeholder" aria-hidden="true"><span/><span/><span/></div>}<a className="text-link" href="#growth">Explore your skills<ArrowRight size={16} aria-hidden="true"/></a></section>
      <section className="connection-note"><span className={`connection-dot ${credential.configured ? 'connected' : ''}`}/><span className="eyebrow">{credential.configured ? 'YOUR MODEL IS CONNECTED' : credential.demo_mode ? 'YOUR DEMO DESK IS READY' : 'ONE SMALL SETUP STEP'}</span><h3>{credential.configured ? credential.model : 'Bring your own AI.'}</h3><p>{credential.configured ? 'New paths use your saved provider connection.' : credential.demo_mode ? 'Try “sentences” now, or connect a model to explore any topic.' : 'Connect OpenAI or Anthropic to start creating your learning paths.'}</p><button className="text-link" onClick={() => navigate('settings')}>{credential.configured ? 'Manage connection' : 'Set up your model'}<ArrowUpRight size={15} aria-hidden="true"/></button></section>
    </aside></div>
  </>;
}

import { useState } from 'react';
import { Search } from 'lucide-react';
export function Library({ practice, courses, open, create }: { practice: boolean; courses: Course[]; open: (course: Course) => void; create: () => void }) {
  const [filter, setFilter] = useState('all'); const [query, setQuery] = useState('');
  const all = courses.filter(course => course.practice === practice);
  const visible = all.filter(course => `${course.title} ${course.topic}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || (filter === 'completed') === course.complete));
  return <><PageHeading eyebrow={practice ? 'SMALL TESTS. USEFUL DISCOVERIES.' : 'YOUR COLLECTION OF CURIOSITIES'} title={practice ? 'The practice studio.' : 'Your learning shelf.'} description={practice ? 'A focused quiz, whenever you need one.' : 'A place for everything you’re learning—and everything you’ve learned.'} action={<Button onClick={create}><Plus size={18} aria-hidden="true"/>{practice ? 'New practice quiz' : 'New learning path'}</Button>}/>
    <div className="library-toolbar"><div className="filter-tabs" aria-label="Filter paths">{['all', 'in progress', 'completed'].map(value => <button key={value} onClick={() => setFilter(value)} aria-pressed={filter === value}>{value === 'all' ? 'All' : value === 'completed' ? 'Completed' : 'In progress'}</button>)}</div><label className="search-field"><Search size={18} aria-hidden="true"/><input aria-label="Search topics" placeholder="Find a topic…" value={query} onChange={event => setQuery(event.target.value)}/></label></div>
    {visible.length ? <div className="path-grid">{visible.map((course, index) => <article className="path-card" key={course.id}><div className={`path-cover cover-${index % 3}`}><span>{practice ? 'PRACTICE NOTES' : 'LEARNING NOTES'}</span><BookOpen size={35} strokeWidth={1.2} aria-hidden="true"/><span className="cover-number">{String(index + 1).padStart(2, '0')}</span></div><div className="path-card-body"><Status complete={course.complete}/><h2>{course.title}</h2><p>{course.complete ? `${course.missions.length} ${practice ? 'quiz' : 'missions'} covered` : `Mission ${course.current + 1} of ${course.missions.length}`}</p><Progress value={course.current / course.missions.length * 100} label={`${course.title} progress`}/><button className="path-card-action" onClick={() => open(course)}>{course.complete ? 'Review results' : course.pending_attempt ? 'Choose next step' : 'Continue learning'}<ArrowRight size={17} aria-hidden="true"/></button></div></article>)}</div> : <Empty title={all.length ? 'No matching topics.' : practice ? 'Give your knowledge a little workout.' : 'Make space for a new interest.'} action={all.length ? () => { setFilter('all'); setQuery(''); } : create} actionLabel={all.length ? 'Clear filters' : practice ? 'Create a practice quiz' : 'Start a learning path'}>{all.length ? 'Try another search or clear your filters.' : 'Start with a topic you care about. The next step is smaller than you think.'}</Empty>}
  </>;
}
