import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, LockKeyhole, Target, Trophy } from 'lucide-react';
import type { Assessment, Course, Result } from '../types';
import { Button, Empty, PageHeading, Progress } from '../components/UI';
export function ResultReview({ result, children }: { result: Assessment; children?: React.ReactNode }) {
  return <section className="result-panel"><div className="result-summary"><div className="result-score"><span>{result.score}</span><small>/100</small></div><div><span className="eyebrow">YOUR CHECK-IN</span><h2>{result.passed ? 'That’s understanding, in action.' : 'Now you know where to focus.'}</h2><p>{result.passed ? 'Keep building on what you know.' : 'A score is a starting point. Take the useful parts with you.'}</p></div></div><div className="result-skills"><div><span className="eyebrow"><Check size={14} aria-hidden="true"/> WORKING WELL</span><p>{result.strengths.join(' · ') || 'Your strengths are still taking shape.'}</p></div><div><span className="eyebrow"><Target size={14} aria-hidden="true"/> NEXT TO PRACTICE</span><p>{result.weaknesses.join(' · ') || 'No gaps found in this quiz.'}</p></div></div><div className="answer-review"><h3>A closer look at your answers</h3>{result.feedback.map((feedback, index) => <details key={index}><summary><span className={`answer-indicator ${feedback.correct ? 'is-correct' : ''}`}>{feedback.correct ? <Check size={14} aria-hidden="true"/> : index + 1}</span><span>Question {index + 1}<small>{feedback.correct ? 'Correct' : 'Worth reviewing'}</small></span><ChevronDown size={17} aria-hidden="true"/></summary><div><strong>{feedback.answer}</strong><p>{feedback.explanation}</p></div></details>)}</div>{children}</section>;
}
type Draft = { answers: Record<number, number>; tasks: Record<number, boolean>; quiz: boolean; skip: boolean };
function readDraft(key: string, practice: boolean): Draft {
  try { const value = JSON.parse(sessionStorage.getItem(key) || 'null'); if (value && value.answers && value.tasks && typeof value.answers === 'object' && typeof value.tasks === 'object' && typeof value.quiz === 'boolean' && typeof value.skip === 'boolean') return value; } catch { /* Storage is optional. */ }
  return { answers: {}, tasks: {}, quiz: practice, skip: false };
}
export function MissionPage({ course, userId, result, pending, busy, onSubmit, onDecision, onReview, onNext }: {
  course: Course; userId: string; result: Result | null; pending?: Assessment; busy: boolean;
  onSubmit: (data: { mission_index: number; answers: number[]; skip: boolean; tasks_completed: boolean }) => Promise<boolean>;
  onDecision: (attemptId: string, remediate: boolean) => void; onReview: () => void; onNext: () => void;
}) {
  const key = `eduquiz:draft:${userId}:${course.id}:${course.current}`;
  const [draft, setDraft] = useState<Draft>(() => readDraft(key, course.practice));
  useEffect(() => { setDraft(readDraft(key, course.practice)); }, [key, course.practice]);
  function update(changes: Partial<Draft>) {
    const next = { ...draft, ...changes }; setDraft(next);
    try { sessionStorage.setItem(key, JSON.stringify(next)); } catch { /* Continue without persistence. */ }
  }
  const mission = course.missions[course.current];
  const assessment = result || pending;
  const tasksDone = (mission?.tasks || []).every((_, index) => !!draft.tasks[index]);
  const answered = (mission?.questions || []).filter((_, index) => Number.isInteger(draft.answers[index])).length;
  const decisionPanel = course.pending_attempt && <div className="decision-panel"><span className="eyebrow">CHOOSE YOUR NEXT STEP</span><h3>Spend a little time on the tricky bits?</h3><p>We can add a focused mission for your weak skills before the next topic. It’s your call.</p><div className="button-row"><Button disabled={busy} onClick={() => onDecision(course.pending_attempt!, true)}>Work on these skills<ArrowRight size={17} aria-hidden="true"/></Button><Button disabled={busy} variant="secondary" onClick={() => onDecision(course.pending_attempt!, false)}>Continue to next topic</Button></div></div>;
  return <><a className="back-link" href={course.practice ? '#practice' : '#learning'}><ArrowLeft size={16} aria-hidden="true"/>Back to {course.practice ? 'practice studio' : 'learning shelf'}</a><PageHeading eyebrow={course.practice ? `${course.topic} / PRACTICE` : `${course.topic} / LEARNING PATH`} title={assessment ? 'A useful moment to reflect.' : course.complete ? 'One more thing you know.' : mission.title}/>
    {assessment ? <ResultReview result={assessment}>{!assessment.can_continue ? <div className="decision-panel"><h3>A little more practice before skipping.</h3><p>Skipping needs a score of at least 80%. Return to the lesson and try again when you’re ready.</p><Button onClick={() => { update({ quiz: false, skip: false, answers: {} }); onNext(); }}>Back to the lesson<ArrowRight size={17} aria-hidden="true"/></Button></div> : decisionPanel || <div className="result-actions"><Button onClick={course.complete ? onReview : onNext}>{course.complete ? 'View growth report' : 'Open next mission'}<ArrowRight size={17} aria-hidden="true"/></Button></div>}</ResultReview>
      : course.pending_attempt ? <section className="panel">{decisionPanel}</section>
      : course.complete ? <Empty title="You reached the end of this path." action={onReview} actionLabel="Review your results">Your quiz results and skills are saved in your growth report.</Empty>
      : <div className="mission-columns"><article className="lesson-panel">
        <div className="lesson-meta"><span className="eyebrow">{draft.quiz ? draft.skip ? 'SKIP CHALLENGE' : 'CHECK YOUR UNDERSTANDING' : 'READ. TRY. REFLECT.'}</span><span>{draft.quiz ? `${answered}/${mission.questions?.length || 0} answered` : `${Object.values(draft.tasks).filter(Boolean).length}/${mission.tasks?.length || 0} tasks complete`}</span></div>
        {draft.quiz ? <><Progress value={answered / (mission.questions?.length || 1) * 100} label="Questions answered"/>{draft.skip && <p className="context-note">You need 80% to skip. If you don’t pass, the lesson stays available.</p>}<form onSubmit={async event => { event.preventDefault(); const success = await onSubmit({ mission_index: course.current, answers: mission.questions!.map((_, index) => draft.answers[index]), skip: draft.skip, tasks_completed: tasksDone }); if (success) { try { sessionStorage.removeItem(key); } catch {} } }}>
          {mission.questions?.map((question, index) => <fieldset className="quiz-question" key={index}><legend><span>{String(index + 1).padStart(2, '0')}</span>{question.prompt}</legend>{question.options.map((option, optionIndex) => <label className={`quiz-option ${draft.answers[index] === optionIndex ? 'selected' : ''}`} key={optionIndex}><input required type="radio" name={`question-${index}`} value={optionIndex} checked={draft.answers[index] === optionIndex} disabled={busy} onChange={() => update({ answers: { ...draft.answers, [index]: optionIndex } })}/><span className="option-letter">{String.fromCharCode(65 + optionIndex)}</span><span>{option}</span>{draft.answers[index] === optionIndex && <Check size={17} aria-hidden="true"/>}</label>)}</fieldset>)}
          <div className="lesson-actions"><Button type="submit" disabled={busy || answered !== mission.questions?.length}>{busy ? 'Checking your answers…' : 'Submit answers'}<ArrowRight size={17} aria-hidden="true"/></Button>{!course.practice && <Button variant="ghost" disabled={busy} onClick={() => update({ quiz: false })}>Back to lesson</Button>}</div></form></>
          : <><h2>{mission.objective}</h2><div className="lesson-text">{mission.lesson?.split('\n').filter(Boolean).map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><section className="task-section"><span className="eyebrow">PUT THE IDEA TO WORK</span><h3>Your turn.</h3><p>Try each task, then mark it done. The quiz checks your understanding.</p>{mission.tasks?.map((task, index) => <label className={`task-item ${draft.tasks[index] ? 'done' : ''}`} key={index}><input type="checkbox" checked={!!draft.tasks[index]} onChange={event => update({ tasks: { ...draft.tasks, [index]: event.target.checked } })}/><span>{task}</span></label>)}</section><div className="lesson-actions"><Button disabled={!tasksDone} onClick={() => update({ quiz: true, skip: false })}>Check my understanding<ArrowRight size={17} aria-hidden="true"/></Button><small>{tasksDone ? 'Ready when you are.' : 'Complete the tasks to unlock the quiz.'}</small></div><button className="text-link skip-challenge" onClick={() => update({ quiz: true, skip: true })}>Already know this? Take the skip challenge<ArrowRight size={15} aria-hidden="true"/></button></>}
      </article><aside className="mission-roadmap"><span className="eyebrow">THE BIGGER PICTURE</span><h2>Your path</h2><p>{course.current} of {course.missions.length} missions covered</p><ol>{course.missions.map((item, index) => <li key={index} className={index === course.current ? 'road-current' : index < course.current ? 'road-done' : ''}><span className="road-index">{index < course.current ? <Check size={15} aria-hidden="true"/> : index === course.current ? index + 1 : <LockKeyhole size={13} aria-hidden="true"/>}</span><div><strong>{item.title}</strong><small>{index < course.current ? 'Covered' : index === course.current ? 'You are here' : 'Coming up'}</small></div></li>)}</ol><div className="roadmap-note"><Trophy size={20} aria-hidden="true"/><p>Understanding takes practice.<br/>You set the pace.</p></div></aside></div>}
  </>;
}
