import { useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, ChevronDown } from 'lucide-react';
import type { Course, Report } from '../types';
import { Button, Empty, PageHeading, Progress } from '../components/UI';
import { MissionRecap } from '../components/MissionRecap';
import { ResultReview } from './Mission';
export function Reports({ report, courses, busy, onExport, onPractice, selectedCourse }: { report: Report; courses: Course[]; busy: boolean; onExport: () => void; onPractice: () => void; selectedCourse?: string }) {
  const [filter, setFilter] = useState(selectedCourse || 'all');
  const [review, setReview] = useState<string | null>(null);
  const attempts = report.attempts.filter(attempt => filter === 'all' || attempt.course_id === filter);
  const recent = attempts.slice(-12);
  const selected = report.attempts.find(attempt => attempt.id === review);
  return <><PageHeading eyebrow="A RECORD OF WHAT’S CLICKING" title="Look how far you’ve come." description="Your scores are feedback—not a finish line." action={<Button variant="secondary" onClick={onExport} disabled={busy || !report.attempts.length}><ArrowDownToLine size={17} aria-hidden="true"/>Export report</Button>}/>
    {!report.attempts.length ? <Empty title="Your progress deserves a place." action={onPractice} actionLabel="Take your first practice quiz">After your first quiz, you’ll see your scores, strengths and skills to revisit here.</Empty> : <><div className="report-columns"><section className="panel"><div className="section-heading"><div><span className="eyebrow">ASSESSMENT HISTORY</span><h2>The learning curve.</h2></div><label className="report-filter"><span className="sr-only">Filter assessment history</span><select value={filter} onChange={event => { setFilter(event.target.value); setReview(null); }}><option value="all">All topics</option>{courses.map(course => <option key={course.id} value={course.id}>{course.topic}{course.practice ? ' · Practice' : ''}</option>)}</select></label></div><p>Last {recent.length} attempts, in order. Select a bar to review its answers.</p>{recent.length ? <div className="score-chart" aria-label="Recent quiz scores">{recent.map((attempt, index) => <button key={attempt.id} onClick={() => setReview(attempt.id)} aria-label={`Quiz ${index + 1}: ${attempt.score} percent. Review answers.`} aria-pressed={review === attempt.id} className="chart-column"><strong>{attempt.score}%</strong><span className="bar-space"><span className="score-bar" style={{ height: `${Math.max(attempt.score, 2)}%` }}/></span><small>{new Date(attempt.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</small></button>)}</div> : <p>No assessments for this path yet.</p>}</section><section className="panel"><span className="eyebrow">ACROSS ALL YOUR PRACTICE</span><h2>Your skill map.</h2><p>Based on your answers so far.</p>{report.skills.map(skill => <div className="report-skill" key={skill.name}><div><strong>{skill.name}</strong><span>{skill.score}%</span></div><Progress value={skill.score} label={`${skill.name} score`}/><small>{skill.evidence} answers · {skill.score >= 80 ? 'A growing strength' : 'Room to practice'}</small></div>)}</section></div>
      {filter !== 'all' && !selected && attempts.length > 0 && <div className="result-recap"><MissionRecap key={filter} courseId={filter}/></div>}
      {selected && <div className="report-review"><div className="section-heading"><h2>Assessment review</h2><Button variant="ghost" onClick={() => setReview(null)}>Close review</Button></div><ResultReview result={selected} recap={{ courseId: selected.course_id, missionIndex: selected.mission_index }}/></div>}
      <section className="panel history-panel"><div className="section-heading"><h2>Your recent sessions</h2><span className="eyebrow">{attempts.length} ASSESSMENTS</span></div>{attempts.slice(-20).reverse().map(attempt => <button className="history-row" key={attempt.id} onClick={() => setReview(review === attempt.id ? null : attempt.id)} aria-expanded={review === attempt.id}><span><strong>{courses.find(course => course.id === attempt.course_id)?.topic || 'Learning path'}</strong><small>{new Date(attempt.date).toLocaleString()}</small></span><span className="history-skill">{attempt.weaknesses.length ? `${attempt.weaknesses.length} skills to revisit` : 'All assessed skills passed'}</span><strong className="history-score">{attempt.score}%</strong><ChevronDown size={17} aria-hidden="true"/></button>)}</section></>}
    <p className="report-disclaimer">Scores combine quiz evidence and may include repeat questions. They are not certifications of mastery.<ArrowUpRight size={14} aria-hidden="true"/></p>
  </>;
}
